MyWedding (ASP Assignment 1)/Controllers/GuestController.cs
using Microsoft.AspNetCore.Mvc;
using MyWedding.Data;
using System.Linq;
using MyWedding.Models.Enums;

namespace MyWedding.Controllers
{
    public class GuestController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public GuestController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        // Custom methods here
        [HttpPost]
        public IActionResult Index([FromForm] string code)
        {
            var guest = _dbContext.Guests.FirstOrDefault(x => x.Code == code);

            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        [HttpPost]
        public IActionResult SaveResponse([FromForm] int id, bool isAttending, EMealType mealType, string comments)
        {
            var guest = _dbContext.Guests.FirstOrDefault(x => x.Id == id);

            guest.IsAttending = isAttending;
            guest.MealType = mealType;
            guest.Comments = comments;
            guest.HasResponded = true;

            _dbContext.Guests.Update(guest);
            _dbContext.SaveChanges();

            return View();
        }
    }
}

MyWedding (ASP Assignment 1)/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyWedding.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

MyWedding (ASP Assignment 1)/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="ui container">
    <h2>@ViewData["Title"].</h2>
    <h3>@ViewData["Message"]</h3>

    <p>Use this area to provide additional information.</p> 
</div>

MyWedding (ASP Assignment 1)/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<div class="ui container">
    <h2>@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <address>
        One Microsoft Way<br/>
        Redmond, WA 98052-6399<br/>
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>
</div>

MyWedding (ASP Assignment 1)/Views/Home/Index.cshtml
<div class="ui segment">

    <div class="ui text container">

        <h1 class="ui header">
            Welcome to our Wedding Response Site
        </h1>

        <p>I cannot add quests to the list, so I cannot check if everything else works or not.</p>
        <p>Authorization is also a problem. The attribute is not recognized by the code</p>

        <div class="ui input">
               <form asp-controller="Guest" asp-action="Index">
                    <input class="ui input" name="code" type="text" placeholder="Your welcome code">
                    <button class="ui primary button" type="submit">Submit</button>
               </form>
        </div>
    </div>

</div>